// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: advertisers.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createAdvertiser = `-- name: CreateAdvertiser :exec
INSERT INTO advertisers (
    id, name
) VALUES (
    $1::uuid, $2::varchar
)
`

type CreateAdvertiserParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateAdvertiser(ctx context.Context, arg CreateAdvertiserParams) error {
	_, err := q.db.Exec(ctx, createAdvertiser, arg.ID, arg.Name)
	return err
}

const getAdvertiserByID = `-- name: GetAdvertiserByID :one
SELECT id, name FROM advertisers
WHERE id = $1::uuid
`

func (q *Queries) GetAdvertiserByID(ctx context.Context, id uuid.UUID) (Advertiser, error) {
	row := q.db.QueryRow(ctx, getAdvertiserByID, id)
	var i Advertiser
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
