// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clicks.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createClick = `-- name: CreateClick :one
INSERT INTO clicks (
    campaign_id, client_id
) VALUES (
    $1::uuid, $2::uuid
)
RETURNING id, campaign_id, client_id
`

type CreateClickParams struct {
	CampaignID uuid.UUID
	ClientID   uuid.UUID
}

func (q *Queries) CreateClick(ctx context.Context, arg CreateClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, createClick, arg.CampaignID, arg.ClientID)
	var i Click
	err := row.Scan(&i.ID, &i.CampaignID, &i.ClientID)
	return i, err
}
