// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: impressions.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createImpression = `-- name: CreateImpression :one
INSERT INTO impressions (
    campaign_id, client_id
) VALUES (
    $1::uuid, $2::uuid
)
RETURNING id, campaign_id, client_id
`

type CreateImpressionParams struct {
	CampaignID uuid.UUID
	ClientID   uuid.UUID
}

func (q *Queries) CreateImpression(ctx context.Context, arg CreateImpressionParams) (Impression, error) {
	row := q.db.QueryRow(ctx, createImpression, arg.CampaignID, arg.ClientID)
	var i Impression
	err := row.Scan(&i.ID, &i.CampaignID, &i.ClientID)
	return i, err
}
