// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"github.com/google/uuid"
)

type Advertiser struct {
	ID   uuid.UUID
	Name string
}

type MlScore struct {
	ClientID     uuid.UUID
	AdvertiserID uuid.UUID
	Score        int32
}

type User struct {
	ID       uuid.UUID
	Login    string
	Age      int32
	Location string
	Gender   string
}
