// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, login, age, location, gender
) VALUES (
    $1::uuid, $2::varchar(50),
    $3::integer, $4::varchar, $5::varchar(7)
)
RETURNING id, login, age, location, gender
`

type CreateUserParams struct {
	ID       uuid.UUID
	Login    string
	Age      int32
	Location string
	Gender   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Login,
		arg.Age,
		arg.Location,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Age,
		&i.Location,
		&i.Gender,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, age, location, gender FROM users
WHERE id = $1::uuid
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Age,
		&i.Location,
		&i.Gender,
	)
	return i, err
}
