// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, login, age, location, gender
) VALUES (
    $1::uuid, $2::varchar(50),
    $3::integer, $4::varchar, $5::varchar(7)
)
`

type CreateUserParams struct {
	ID       uuid.UUID
	Login    string
	Age      int32
	Location string
	Gender   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Login,
		arg.Age,
		arg.Location,
		arg.Gender,
	)
	return err
}
